---
language: go
env:
  - GO111MODULE=on
go:
  - "1.11.x"

script:
  - make

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux